# Builds and tests rakudo for different configurations
# For appveyor.yml syntax reference, please see
# https://www.appveyor.com/docs/appveyor-yml
#
# JVM is already preinstalled in build worker. Please see
# https://www.appveyor.com/docs/installed-software#java
#

# Platforms (e.g. x64, x86)
platform:
  - x86

# Operating system (build VM template)
os: Visual Studio 2017

configuration:
  - Release

# To stop automatic build of VS solution files
build: off

# Build configurations
environment:
  matrix:
      - RAKUDO_OPTIONS: --prefix=C:\rakudo\ --backends=moar --gen-nqp        --gen-moar

# Installation
install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd"'
  - appveyor-retry choco install strawberryperl --version 5.20.1.1 --allow-empty-checksums
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - ECHO %RAKUDO_OPTIONS%
  - CD %APPVEYOR_BUILD_FOLDER%

# Testing
test_script:
  - perl Configure.pl %RAKUDO_OPTIONS%
  - nmake install

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
